name: ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - run: corepack enable
      - run: pnpm i --frozen-lockfile
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build
